services:

  mysql:
    image: mysql:8.4
    container_name: mysql-microservicios
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_carrito
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microservicios-net

  eureka-server:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: on-failure
    networks:
      microservicios-net:
        aliases:
          - smartfood

  ms-carrito:
    build:
      context: ./ms-carrito
      dockerfile: Dockerfile
    container_name: ms-carrito
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  ms-catalogo:
    build:
      context: ./ms-catalogo
      dockerfile: Dockerfile
    container_name: ms-catalogo
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  ms-clientes:
    build:
      context: ./ms-clientes
      dockerfile: Dockerfile
    container_name: ms-clientes
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  ms-despacho:
    build:
      context: ./ms-despacho
      dockerfile: Dockerfile
    container_name: ms-despacho
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  ms-inventario:
    build:
      context: ./ms-inventario
      dockerfile: Dockerfile
    container_name: ms-inventario
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  ms-notificaciones:
    build:
      context: ./ms-notificaciones
      dockerfile: Dockerfile
    container_name: ms-notificaciones
    ports:
      - "8086:8086"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  ms-pagos:
    build:
      context: ./ms-pagos
      dockerfile: Dockerfile
    container_name: ms-pagos
    ports:
      - "8087:8087"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  ms-pedidos:
    build:
      context: ./ms-pedidos
      dockerfile: Dockerfile
    container_name: ms-pedidos
    ports:
      - "8088:8088"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  ms-promociones:
    build:
      context: ./ms-promociones
      dockerfile: Dockerfile
    container_name: ms-promociones
    ports:
      - "8089:8089"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  ms-reportes:
    build:
      context: ./ms-reportes
      dockerfile: Dockerfile
    container_name: ms-reportes
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

  api-gateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      eureka-server:
        condition: service_started
      ms-carrito:
        condition: service_started
      ms-catalogo:
        condition: service_started
      ms-clientes:
        condition: service_started
      ms-despacho:
        condition: service_started
      ms-inventario:
        condition: service_started
      ms-notificaciones:
        condition: service_started
      ms-pagos:
        condition: service_started
      ms-pedidos:
        condition: service_started
      ms-promociones:
        condition: service_started
      ms-reportes:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net

volumes:
  mysql-data:

networks:
  microservicios-net:
    driver: bridge