server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ruta-ms-carrito
          uri: lb://ms-carrito
          predicates:
            - Path=/api/carrito,/api/carrito/**

        - id: ruta-ms-catalogo
          uri: lb://ms-catalogo
          predicates:
            - Path=/api/catalogo,/api/catalogo/**

        - id: ruta-ms-clientes
          uri: lb://ms-clientes
          predicates:
            - Path=/api/clientes,/api/clientes/**

        - id: ruta-ms-despacho
          uri: lb://ms-despacho
          predicates:
            - Path=/api/despacho,/api/despacho/**

        - id: ruta-ms-inventario
          uri: lb://ms-inventario
          predicates:
            - Path=/api/inventario,/api/inventario/**

        - id: ruta-ms-notificaciones
          uri: lb://ms-notificaciones
          predicates:
            - Path=/api/notificaciones,/api/notificaciones/**

        - id: ruta-ms-pagos
          uri: lb://ms-pagos
          predicates:
            - Path=/api/pagos,/api/pagos/**

        - id: ruta-ms-pedidos
          uri: lb://ms-pedidos
          predicates:
            - Path=/api/pedidos,/api/pedidos/**

        - id: ruta-ms-promociones
          uri: lb://ms-promociones
          predicates:
            - Path=/api/promociones,/api/promociones/**

        - id: ruta-ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/api/reportes,/api/reportes/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://smartfood:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: api-gateway:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.server.AccessLog: DEBUG